### ISSUE TITLE
Add QR Code for repository

### ISSUE THREAD

**Issue by pserwylo** [dervishe-/f-droid-web#11]
Looking good mate. Can I suggest you add a QR code for the repo itself. Something along the lines of what the Guardian Project team did: https://guardianproject.info/fdroid/repo/

Then we get the best of both worlds, a page which lets people browse and install from the browser (what you are doing) but also a quick way to get the repo imported into F-Droid itself.

**Comment by dervishe-** [comment]
That's a pretty good idea.

**Comment by dervishe-** [comment]
done
